version: '3'
services:
  web:    
    container_name: web-server    
    build: .
    image: hola-docker-2:1.0
    ports:
      - 80:5000
    environment:
      MSG: ${MSG_CONTAINER}
    volumes:
      - ${HTML_PATH}:/app
  database:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - dbdata:/var/lib/postgresql/data #set dbdata volume
volumes:
  dbdata:
    driver: local